namespace PGS.Controls
{
    partial class CompanyTypeList
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.Data.SortDescriptor sortDescriptor1 = new Telerik.WinControls.Data.SortDescriptor();
            this.gridCoType = new Telerik.WinControls.UI.RadGridView();
            this.coTypeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.gridCoType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridCoType.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.coTypeBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // gridCoType
            // 
            this.gridCoType.AutoSizeRows = true;
            this.gridCoType.BackColor = System.Drawing.SystemColors.Control;
            this.gridCoType.Cursor = System.Windows.Forms.Cursors.Default;
            this.gridCoType.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridCoType.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.gridCoType.ForeColor = System.Drawing.SystemColors.ControlText;
            this.gridCoType.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.gridCoType.Location = new System.Drawing.Point(0, 0);
            // 
            // gridCoType
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "CoType_ID";
            gridViewDecimalColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDecimalColumn1.HeaderText = "CoType_ID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "CoType_ID";
            gridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewTextBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn1.FormatString = "";
            gridViewTextBoxColumn1.HeaderText = "No";
            gridViewTextBoxColumn1.Name = "No";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewTextBoxColumn1.Width = 26;
            gridViewTextBoxColumn2.FieldName = "CoCode";
            gridViewTextBoxColumn2.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn2.FormatString = "";
            gridViewTextBoxColumn2.HeaderText = "Code";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "CoCode";
            gridViewTextBoxColumn2.Width = 100;
            gridViewTextBoxColumn3.FieldName = "CoName";
            gridViewTextBoxColumn3.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn3.FormatString = "";
            gridViewTextBoxColumn3.HeaderText = "Name";
            gridViewTextBoxColumn3.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "CoName";
            gridViewTextBoxColumn3.Width = 150;
            gridViewTextBoxColumn4.FieldName = "CoNotes";
            gridViewTextBoxColumn4.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn4.FormatString = "";
            gridViewTextBoxColumn4.HeaderText = "Notes";
            gridViewTextBoxColumn4.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Multiline = true;
            gridViewTextBoxColumn4.Name = "CoNotes";
            gridViewTextBoxColumn4.Width = 250;
            gridViewTextBoxColumn4.WrapText = true;
            gridViewCheckBoxColumn1.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn1.FieldName = "Active";
            gridViewCheckBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewCheckBoxColumn1.FormatString = "";
            gridViewCheckBoxColumn1.HeaderText = "Active";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MinWidth = 20;
            gridViewCheckBoxColumn1.Name = "Active";
            gridViewCheckBoxColumn1.Width = 56;
            gridViewDateTimeColumn1.DataType = typeof(System.Nullable<System.DateTime>);
            gridViewDateTimeColumn1.FieldName = "UpdatedDate";
            gridViewDateTimeColumn1.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            gridViewDateTimeColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDateTimeColumn1.HeaderText = "UpdatedDate";
            gridViewDateTimeColumn1.IsAutoGenerated = true;
            gridViewDateTimeColumn1.IsVisible = false;
            gridViewDateTimeColumn1.Name = "UpdatedDate";
            gridViewTextBoxColumn5.DataType = typeof(System.Collections.Generic.ICollection<PGS.Entity.Supplier>);
            gridViewTextBoxColumn5.FieldName = "Suppliers";
            gridViewTextBoxColumn5.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn5.HeaderText = "Suppliers";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.IsVisible = false;
            gridViewTextBoxColumn5.Name = "Suppliers";
            this.gridCoType.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewCheckBoxColumn1,
            gridViewDateTimeColumn1,
            gridViewTextBoxColumn5});
            this.gridCoType.MasterTemplate.DataSource = this.coTypeBindingSource;
            sortDescriptor1.PropertyName = "CoCode";
            this.gridCoType.MasterTemplate.SortDescriptors.AddRange(new Telerik.WinControls.Data.SortDescriptor[] {
            sortDescriptor1});
            this.gridCoType.Name = "gridCoType";
            this.gridCoType.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridCoType.RightToLeft = System.Windows.Forms.RightToLeft.No;
            // 
            // 
            // 
            this.gridCoType.RootElement.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridCoType.Size = new System.Drawing.Size(633, 427);
            this.gridCoType.TabIndex = 0;
            this.gridCoType.CellFormatting += new Telerik.WinControls.UI.CellFormattingEventHandler(this.gridCoType_CellFormatting);
            this.gridCoType.CellValidating += new Telerik.WinControls.UI.CellValidatingEventHandler(this.gridCoType_CellValidating);
            this.gridCoType.UserAddingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridCoType_UserAddingRow);
            this.gridCoType.UserAddedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridCoType_UserAddedRow);
            this.gridCoType.UserDeletingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridCoType_UserDeletingRow);
            this.gridCoType.UserDeletedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridCoType_UserDeletedRow);
            this.gridCoType.CellValueChanged += new Telerik.WinControls.UI.GridViewCellEventHandler(this.gridCoType_CellValueChanged);
            this.gridCoType.DataBindingComplete += new Telerik.WinControls.UI.GridViewBindingCompleteEventHandler(this.gridCoType_DataBindingComplete);
            // 
            // coTypeBindingSource
            // 
            this.coTypeBindingSource.DataSource = typeof(PGS.Entity.CoType);
            // 
            // CompanyTypeList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.gridCoType);
            this.Name = "CompanyTypeList";
            this.Size = new System.Drawing.Size(633, 427);
            ((System.ComponentModel.ISupportInitialize)(this.gridCoType.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridCoType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.coTypeBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView gridCoType;
        private System.Windows.Forms.BindingSource coTypeBindingSource;
    }
}
