namespace PGS.Controls
{
    partial class DepartmentList
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn6 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn7 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.Data.SortDescriptor sortDescriptor1 = new Telerik.WinControls.Data.SortDescriptor();
            this.gridDepartments = new Telerik.WinControls.UI.RadGridView();
            this.departmentBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.gridDepartments)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.departmentBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // gridDepartments
            // 
            this.gridDepartments.BackColor = System.Drawing.SystemColors.Control;
            this.gridDepartments.Cursor = System.Windows.Forms.Cursors.Default;
            this.gridDepartments.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridDepartments.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.gridDepartments.ForeColor = System.Drawing.SystemColors.ControlText;
            this.gridDepartments.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.gridDepartments.Location = new System.Drawing.Point(0, 0);
            // 
            // gridDepartments
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "DeptID";
            gridViewDecimalColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDecimalColumn1.HeaderText = "DeptID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "DeptID";
            gridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewTextBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn1.HeaderText = "No";
            gridViewTextBoxColumn1.Name = "No";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.Width = 24;
            gridViewTextBoxColumn2.FieldName = "DeptCode";
            gridViewTextBoxColumn2.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn2.HeaderText = "Code";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "DeptCode";
            gridViewTextBoxColumn2.Width = 142;
            gridViewTextBoxColumn3.FieldName = "DeptName";
            gridViewTextBoxColumn3.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn3.HeaderText = "Name";
            gridViewTextBoxColumn3.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "DeptName";
            gridViewTextBoxColumn3.Width = 230;
            gridViewDecimalColumn2.DataType = typeof(System.Nullable<int>);
            gridViewDecimalColumn2.FieldName = "ParentID";
            gridViewDecimalColumn2.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDecimalColumn2.HeaderText = "ParentID";
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.IsVisible = false;
            gridViewDecimalColumn2.Name = "ParentID";
            gridViewDecimalColumn2.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewTextBoxColumn4.FieldName = "DeptNotes";
            gridViewTextBoxColumn4.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn4.HeaderText = "Notes";
            gridViewTextBoxColumn4.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Multiline = true;
            gridViewTextBoxColumn4.Name = "DeptNotes";
            gridViewTextBoxColumn4.Width = 266;
            gridViewTextBoxColumn4.WrapText = true;
            gridViewCheckBoxColumn1.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn1.FieldName = "Active";
            gridViewCheckBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewCheckBoxColumn1.HeaderText = "Active";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MinWidth = 20;
            gridViewCheckBoxColumn1.Name = "Active";
            gridViewDateTimeColumn1.DataType = typeof(System.Nullable<System.DateTime>);
            gridViewDateTimeColumn1.FieldName = "UpdatedDate";
            gridViewDateTimeColumn1.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            gridViewDateTimeColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDateTimeColumn1.HeaderText = "UpdatedDate";
            gridViewDateTimeColumn1.IsAutoGenerated = true;
            gridViewDateTimeColumn1.IsVisible = false;
            gridViewDateTimeColumn1.Name = "UpdatedDate";
            gridViewTextBoxColumn5.DataType = typeof(System.Collections.Generic.ICollection<PGS.Entity.Mat_Requests>);
            gridViewTextBoxColumn5.FieldName = "Mat_Requests_ReceiveDept";
            gridViewTextBoxColumn5.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn5.HeaderText = "Mat_Requests_ReceiveDept";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.IsVisible = false;
            gridViewTextBoxColumn5.Name = "Mat_Requests_ReceiveDept";
            gridViewTextBoxColumn6.DataType = typeof(System.Collections.Generic.ICollection<PGS.Entity.Mat_Requests>);
            gridViewTextBoxColumn6.FieldName = "Mat_Requests_SendDept";
            gridViewTextBoxColumn6.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn6.HeaderText = "Mat_Requests_SendDept";
            gridViewTextBoxColumn6.IsAutoGenerated = true;
            gridViewTextBoxColumn6.IsVisible = false;
            gridViewTextBoxColumn6.Name = "Mat_Requests_SendDept";
            gridViewTextBoxColumn7.DataType = typeof(System.Collections.Generic.ICollection<PGS.Entity.User>);
            gridViewTextBoxColumn7.FieldName = "Users";
            gridViewTextBoxColumn7.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn7.HeaderText = "Users";
            gridViewTextBoxColumn7.IsAutoGenerated = true;
            gridViewTextBoxColumn7.IsVisible = false;
            gridViewTextBoxColumn7.Name = "Users";
            this.gridDepartments.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewDecimalColumn2,
            gridViewTextBoxColumn4,
            gridViewCheckBoxColumn1,
            gridViewDateTimeColumn1,
            gridViewTextBoxColumn5,
            gridViewTextBoxColumn6,
            gridViewTextBoxColumn7});
            this.gridDepartments.MasterTemplate.DataSource = this.departmentBindingSource;
            sortDescriptor1.PropertyName = "DeptNotes";
            this.gridDepartments.MasterTemplate.SortDescriptors.AddRange(new Telerik.WinControls.Data.SortDescriptor[] {
            sortDescriptor1});
            this.gridDepartments.Name = "gridDepartments";
            this.gridDepartments.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridDepartments.RightToLeft = System.Windows.Forms.RightToLeft.No;
            // 
            // 
            // 
            this.gridDepartments.RootElement.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridDepartments.Size = new System.Drawing.Size(745, 458);
            this.gridDepartments.TabIndex = 0;
            this.gridDepartments.CellFormatting += new Telerik.WinControls.UI.CellFormattingEventHandler(this.gridDepartments_CellFormatting);
            this.gridDepartments.CellValidating += new Telerik.WinControls.UI.CellValidatingEventHandler(this.gridDepartments_CellValidating);
            this.gridDepartments.UserAddingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridDepartments_UserAddingRow);
            this.gridDepartments.UserAddedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridDepartments_UserAddedRow);
            this.gridDepartments.UserDeletingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridDepartments_UserDeletingRow);
            this.gridDepartments.UserDeletedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridDepartments_UserDeletedRow);
            this.gridDepartments.CellValueChanged += new Telerik.WinControls.UI.GridViewCellEventHandler(this.gridDepartments_CellValueChanged);
            this.gridDepartments.DataBindingComplete += new Telerik.WinControls.UI.GridViewBindingCompleteEventHandler(this.gridDepartments_DataBindingComplete);
            // 
            // departmentBindingSource
            // 
            this.departmentBindingSource.DataSource = typeof(PGS.Entity.Department);
            // 
            // DepartmentList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.gridDepartments);
            this.Name = "DepartmentList";
            this.Size = new System.Drawing.Size(745, 458);
            ((System.ComponentModel.ISupportInitialize)(this.gridDepartments)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.departmentBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView gridDepartments;
        private System.Windows.Forms.BindingSource departmentBindingSource;
    }
}
