namespace PGS.Controls
{
    partial class EQ_CategoryList
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.Data.SortDescriptor sortDescriptor1 = new Telerik.WinControls.Data.SortDescriptor();
            this.gridEQCategory = new Telerik.WinControls.UI.RadGridView();
            this.eQCategoriesBindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.eQCategoriesBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.gridEQCategory)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridEQCategory.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.eQCategoriesBindingSource1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.eQCategoriesBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // gridEQCategory
            // 
            this.gridEQCategory.AutoSizeRows = true;
            this.gridEQCategory.BackColor = System.Drawing.SystemColors.Control;
            this.gridEQCategory.Cursor = System.Windows.Forms.Cursors.Default;
            this.gridEQCategory.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridEQCategory.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.gridEQCategory.ForeColor = System.Drawing.SystemColors.ControlText;
            this.gridEQCategory.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.gridEQCategory.Location = new System.Drawing.Point(0, 0);
            // 
            // gridEQCategory
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "EQCatID";
            gridViewDecimalColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDecimalColumn1.HeaderText = "EQCatID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "EQCatID";
            gridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewTextBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn1.FormatString = "";
            gridViewTextBoxColumn1.HeaderText = "No";
            gridViewTextBoxColumn1.Name = "No";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewTextBoxColumn1.Width = 24;
            gridViewTextBoxColumn2.FieldName = "Code";
            gridViewTextBoxColumn2.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn2.FormatString = "";
            gridViewTextBoxColumn2.HeaderText = "Code";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "Code";
            gridViewTextBoxColumn2.Width = 96;
            gridViewTextBoxColumn3.FieldName = "Name";
            gridViewTextBoxColumn3.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn3.FormatString = "";
            gridViewTextBoxColumn3.HeaderText = "Category name";
            gridViewTextBoxColumn3.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "Name";
            gridViewTextBoxColumn3.Width = 280;
            gridViewTextBoxColumn4.FieldName = "Description";
            gridViewTextBoxColumn4.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn4.FormatString = "";
            gridViewTextBoxColumn4.HeaderText = "Description";
            gridViewTextBoxColumn4.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Multiline = true;
            gridViewTextBoxColumn4.Name = "Description";
            gridViewTextBoxColumn4.RowSpan = 40;
            gridViewTextBoxColumn4.Width = 300;
            gridViewTextBoxColumn4.WrapText = true;
            gridViewCheckBoxColumn1.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn1.FieldName = "Active";
            gridViewCheckBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewCheckBoxColumn1.FormatString = "";
            gridViewCheckBoxColumn1.HeaderText = "Active";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MinWidth = 20;
            gridViewCheckBoxColumn1.Name = "Active";
            gridViewDateTimeColumn1.DataType = typeof(System.Nullable<System.DateTime>);
            gridViewDateTimeColumn1.FieldName = "UpdatedDate";
            gridViewDateTimeColumn1.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            gridViewDateTimeColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDateTimeColumn1.HeaderText = "UpdatedDate";
            gridViewDateTimeColumn1.IsAutoGenerated = true;
            gridViewDateTimeColumn1.IsVisible = false;
            gridViewDateTimeColumn1.Name = "UpdatedDate";
            gridViewTextBoxColumn5.DataType = typeof(System.Collections.Generic.ICollection<PGS.Entity.Equipment>);
            gridViewTextBoxColumn5.FieldName = "Equipments";
            gridViewTextBoxColumn5.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn5.HeaderText = "Equipments";
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.IsVisible = false;
            gridViewTextBoxColumn5.Name = "Equipments";
            this.gridEQCategory.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewCheckBoxColumn1,
            gridViewDateTimeColumn1,
            gridViewTextBoxColumn5});
            this.gridEQCategory.MasterTemplate.DataSource = this.eQCategoriesBindingSource1;
            this.gridEQCategory.MasterTemplate.EnableAlternatingRowColor = true;
            sortDescriptor1.PropertyName = "Code";
            this.gridEQCategory.MasterTemplate.SortDescriptors.AddRange(new Telerik.WinControls.Data.SortDescriptor[] {
            sortDescriptor1});
            this.gridEQCategory.Name = "gridEQCategory";
            this.gridEQCategory.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridEQCategory.RightToLeft = System.Windows.Forms.RightToLeft.No;
            // 
            // 
            // 
            this.gridEQCategory.RootElement.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridEQCategory.Size = new System.Drawing.Size(626, 416);
            this.gridEQCategory.TabIndex = 0;
            this.gridEQCategory.CellFormatting += new Telerik.WinControls.UI.CellFormattingEventHandler(this.gridEQCategory_CellFormatting);
            this.gridEQCategory.CellValidating += new Telerik.WinControls.UI.CellValidatingEventHandler(this.gridEQCategory_CellValidating);
            this.gridEQCategory.UserAddingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridEQCategory_UserAddingRow);
            this.gridEQCategory.UserAddedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridEQCategory_UserAddedRow);
            this.gridEQCategory.UserDeletingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridEQCategory_UserDeletingRow);
            this.gridEQCategory.UserDeletedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridEQCategory_UserDeletedRow);
            this.gridEQCategory.CellValueChanged += new Telerik.WinControls.UI.GridViewCellEventHandler(this.gridEQCategory_CellValueChanged);
            this.gridEQCategory.DataBindingComplete += new Telerik.WinControls.UI.GridViewBindingCompleteEventHandler(this.gridEQCategory_DataBindingComplete);
            // 
            // eQCategoriesBindingSource1
            // 
            this.eQCategoriesBindingSource1.DataSource = typeof(PGS.Entity.EQ_Categories);
            // 
            // eQCategoriesBindingSource
            // 
            this.eQCategoriesBindingSource.DataSource = typeof(PGS.Entity.EQ_Categories);
            // 
            // EQ_CategoryList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.gridEQCategory);
            this.Name = "EQ_CategoryList";
            this.Size = new System.Drawing.Size(626, 416);
            ((System.ComponentModel.ISupportInitialize)(this.gridEQCategory.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridEQCategory)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.eQCategoriesBindingSource1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.eQCategoriesBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView gridEQCategory;
        private System.Windows.Forms.BindingSource eQCategoriesBindingSource;
        private System.Windows.Forms.BindingSource eQCategoriesBindingSource1;
    }
}
