namespace PGS.Controls
{
    partial class UserList
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewMultiComboBoxColumn gridViewMultiComboBoxColumn1 = new Telerik.WinControls.UI.GridViewMultiComboBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewComboBoxColumn gridViewComboBoxColumn1 = new Telerik.WinControls.UI.GridViewComboBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn2 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn5 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn6 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn7 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn8 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            this.employeeBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.gridUsers = new Telerik.WinControls.UI.RadGridView();
            this.userBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridUsers.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.userBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // employeeBindingSource
            // 
            this.employeeBindingSource.DataSource = typeof(PGS.Entity.Employee);
            // 
            // gridUsers
            // 
            this.gridUsers.BackColor = System.Drawing.SystemColors.Control;
            this.gridUsers.Cursor = System.Windows.Forms.Cursors.Default;
            this.gridUsers.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridUsers.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.gridUsers.ForeColor = System.Drawing.SystemColors.ControlText;
            this.gridUsers.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.gridUsers.Location = new System.Drawing.Point(0, 0);
            // 
            // gridUsers
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "UserID";
            gridViewDecimalColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDecimalColumn1.HeaderText = "UserID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "UserID";
            gridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleRight;
            gridViewTextBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn1.HeaderText = "No";
            gridViewTextBoxColumn1.Name = "No";
            gridViewTextBoxColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.Width = 24;
            gridViewMultiComboBoxColumn1.DataType = typeof(System.Nullable<int>);
            gridViewMultiComboBoxColumn1.DisplayMember = null;
            gridViewMultiComboBoxColumn1.DropDownStyle = Telerik.WinControls.RadDropDownStyle.DropDown;
            gridViewMultiComboBoxColumn1.FieldName = "EmployeeID";
            gridViewMultiComboBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewMultiComboBoxColumn1.HeaderText = "Employee";
            gridViewMultiComboBoxColumn1.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewMultiComboBoxColumn1.Name = "FullName";
            gridViewMultiComboBoxColumn1.ValueMember = null;
            gridViewMultiComboBoxColumn1.Width = 120;
            gridViewTextBoxColumn2.FieldName = "UserName";
            gridViewTextBoxColumn2.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn2.HeaderText = "UserName";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "UserName";
            gridViewTextBoxColumn2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewTextBoxColumn2.Width = 120;
            gridViewTextBoxColumn3.FieldName = "UserPwd";
            gridViewTextBoxColumn3.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn3.HeaderText = "Password";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "UserPwd";
            gridViewTextBoxColumn3.Width = 120;
            gridViewTextBoxColumn4.FieldName = "UserPosition";
            gridViewTextBoxColumn4.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn4.HeaderText = "Position";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "UserPosition";
            gridViewTextBoxColumn4.Width = 180;
            gridViewComboBoxColumn1.DataType = typeof(System.Nullable<int>);
            gridViewComboBoxColumn1.DisplayMember = null;
            gridViewComboBoxColumn1.FieldName = "DeptID";
            gridViewComboBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewComboBoxColumn1.HeaderText = "Department";
            gridViewComboBoxColumn1.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewComboBoxColumn1.Name = "DeptID";
            gridViewComboBoxColumn1.ValueMember = null;
            gridViewComboBoxColumn1.Width = 140;
            gridViewCheckBoxColumn1.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn1.FieldName = "Active";
            gridViewCheckBoxColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewCheckBoxColumn1.HeaderText = "Active";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MinWidth = 20;
            gridViewCheckBoxColumn1.Name = "Active";
            gridViewCheckBoxColumn2.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn2.FieldName = "IsLogin";
            gridViewCheckBoxColumn2.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewCheckBoxColumn2.HeaderText = "IsLogin";
            gridViewCheckBoxColumn2.IsAutoGenerated = true;
            gridViewCheckBoxColumn2.MinWidth = 20;
            gridViewCheckBoxColumn2.Name = "IsLogin";
            gridViewTextBoxColumn5.FieldName = "UserNotes";
            gridViewTextBoxColumn5.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn5.HeaderText = "Notes";
            gridViewTextBoxColumn5.HeaderTextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            gridViewTextBoxColumn5.IsAutoGenerated = true;
            gridViewTextBoxColumn5.Multiline = true;
            gridViewTextBoxColumn5.Name = "UserNotes";
            gridViewTextBoxColumn5.Width = 250;
            gridViewTextBoxColumn5.WrapText = true;
            gridViewDateTimeColumn1.DataType = typeof(System.Nullable<System.DateTime>);
            gridViewDateTimeColumn1.FieldName = "UpdatedDate";
            gridViewDateTimeColumn1.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            gridViewDateTimeColumn1.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewDateTimeColumn1.HeaderText = "UpdatedDate";
            gridViewDateTimeColumn1.IsAutoGenerated = true;
            gridViewDateTimeColumn1.IsVisible = false;
            gridViewDateTimeColumn1.Name = "UpdatedDate";
            gridViewTextBoxColumn6.DataType = typeof(PGS.Entity.Department);
            gridViewTextBoxColumn6.FieldName = "Department";
            gridViewTextBoxColumn6.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn6.HeaderText = "Department";
            gridViewTextBoxColumn6.IsAutoGenerated = true;
            gridViewTextBoxColumn6.IsVisible = false;
            gridViewTextBoxColumn6.Name = "Department";
            gridViewTextBoxColumn7.DataType = typeof(PGS.Entity.Employee);
            gridViewTextBoxColumn7.FieldName = "Employee";
            gridViewTextBoxColumn7.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn7.HeaderText = "Employee";
            gridViewTextBoxColumn7.IsAutoGenerated = true;
            gridViewTextBoxColumn7.IsVisible = false;
            gridViewTextBoxColumn7.Name = "Employee";
            gridViewTextBoxColumn8.DataType = typeof(System.Collections.Generic.ICollection<PGS.Entity.UserRole>);
            gridViewTextBoxColumn8.FieldName = "UserRoles";
            gridViewTextBoxColumn8.FormatInfo = new System.Globalization.CultureInfo("");
            gridViewTextBoxColumn8.HeaderText = "User Roles";
            gridViewTextBoxColumn8.IsAutoGenerated = true;
            gridViewTextBoxColumn8.Name = "UserRoles";
            gridViewTextBoxColumn8.ReadOnly = true;
            gridViewTextBoxColumn8.Width = 180;
            this.gridUsers.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewMultiComboBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewTextBoxColumn4,
            gridViewComboBoxColumn1,
            gridViewCheckBoxColumn1,
            gridViewCheckBoxColumn2,
            gridViewTextBoxColumn5,
            gridViewDateTimeColumn1,
            gridViewTextBoxColumn6,
            gridViewTextBoxColumn7,
            gridViewTextBoxColumn8});
            this.gridUsers.MasterTemplate.DataSource = this.userBindingSource;
            this.gridUsers.Name = "gridUsers";
            this.gridUsers.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridUsers.RightToLeft = System.Windows.Forms.RightToLeft.No;
            // 
            // 
            // 
            this.gridUsers.RootElement.Padding = new System.Windows.Forms.Padding(0, 0, 0, 1);
            this.gridUsers.Size = new System.Drawing.Size(700, 500);
            this.gridUsers.TabIndex = 0;
            this.gridUsers.CellFormatting += new Telerik.WinControls.UI.CellFormattingEventHandler(this.gridUsers_CellFormatting);
            this.gridUsers.CellBeginEdit += new Telerik.WinControls.UI.GridViewCellCancelEventHandler(this.gridUsers_CellBeginEdit);
            this.gridUsers.CellValidating += new Telerik.WinControls.UI.CellValidatingEventHandler(this.gridUsers_CellValidating);
            this.gridUsers.UserAddingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridUsers_UserAddingRow);
            this.gridUsers.UserAddedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridUsers_UserAddedRow);
            this.gridUsers.UserDeletingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.gridUsers_UserDeletingRow);
            this.gridUsers.UserDeletedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.gridUsers_UserDeletedRow);
            this.gridUsers.CellValueChanged += new Telerik.WinControls.UI.GridViewCellEventHandler(this.gridUsers_CellValueChanged);
            this.gridUsers.DataBindingComplete += new Telerik.WinControls.UI.GridViewBindingCompleteEventHandler(this.gridUsers_DataBindingComplete);
            // 
            // userBindingSource
            // 
            this.userBindingSource.DataSource = typeof(PGS.Entity.User);
            // 
            // UserList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.gridUsers);
            this.Name = "UserList";
            this.Size = new System.Drawing.Size(700, 500);
            ((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridUsers.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridUsers)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.userBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView gridUsers;
        private System.Windows.Forms.BindingSource userBindingSource;
        private System.Windows.Forms.BindingSource employeeBindingSource;
    }
}
