//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Car_Drivers = new HashSet<Car_Drivers>();
            this.Car_Maintenances = new HashSet<Car_Maintenances>();
            this.Car_Schedules = new HashSet<Car_Schedules>();
        }
    
        public int CarID { get; set; }
        public string CarModel { get; set; }
        public string CarName { get; set; }
        public string CarNumber { get; set; }
        public string CarDescription { get; set; }
        public Nullable<double> CarNoms { get; set; }
        public Nullable<System.DateTime> BoughtDate { get; set; }
        public Nullable<double> KMRuns { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Car_Drivers> Car_Drivers { get; set; }
        public virtual ICollection<Car_Maintenances> Car_Maintenances { get; set; }
        public virtual ICollection<Car_Schedules> Car_Schedules { get; set; }
    }
}
