//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Schedules
    {
        public int ScheduleID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string RequestPerson { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> DistanceUsed { get; set; }
        public Nullable<double> BenzinUsed { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Car_Drivers Car_Drivers { get; set; }
        public virtual Car Car { get; set; }
    }
}
