//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Maintenances
    {
        public int MaintenanceID { get; set; }
        public string RequestPerson { get; set; }
        public string RequestReason { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<System.DateTime> MaintenanceBeginDate { get; set; }
        public Nullable<System.DateTime> MaintenanceEndDate { get; set; }
        public string MaintenanceType { get; set; }
        public Nullable<decimal> MaintenanceCost { get; set; }
        public string AfterMaintenance { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
