//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Drivers
    {
        public Car_Drivers()
        {
            this.Car_Schedules = new HashSet<Car_Schedules>();
        }
    
        public int Driver_ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CarID { get; set; }
        public string DriverLicense { get; set; }
        public string DriverInfo { get; set; }
        public string DriverNotes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Car_Schedules> Car_Schedules { get; set; }
    }
}
