//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoType
    {
        public CoType()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int CoType_ID { get; set; }
        public string CoCode { get; set; }
        public string CoName { get; set; }
        public string CoNotes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
