//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Mat_Requests_ReceiveDept = new HashSet<Mat_Requests>();
            this.Mat_Requests_SendDept = new HashSet<Mat_Requests>();
            this.Users = new HashSet<User>();
        }
    
        public int DeptID { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string DeptNotes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Mat_Requests> Mat_Requests_ReceiveDept { get; set; }
        public virtual ICollection<Mat_Requests> Mat_Requests_SendDept { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
