//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQ_InputQuote
    {
        public int InputQuoteID { get; set; }
        public Nullable<int> InputID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EQ_Inputs EQ_Inputs { get; set; }
        public virtual EQ_Quotes EQ_Quotes { get; set; }
    }
}
