//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQ_Inputs
    {
        public EQ_Inputs()
        {
            this.EQ_Input_Details = new HashSet<EQ_Input_Details>();
            this.EQ_InputOrder = new HashSet<EQ_InputOrder>();
            this.EQ_InputQuote = new HashSet<EQ_InputQuote>();
        }
    
        public int Input_ID { get; set; }
        public Nullable<int> StoreIDReceive { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<EQ_Input_Details> EQ_Input_Details { get; set; }
        public virtual ICollection<EQ_InputOrder> EQ_InputOrder { get; set; }
        public virtual ICollection<EQ_InputQuote> EQ_InputQuote { get; set; }
        public virtual Store Store { get; set; }
    }
}
