//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQ_Inventory
    {
        public int InventoryID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<double> MinQuantity { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Store Store { get; set; }
    }
}
