//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQ_Orders
    {
        public EQ_Orders()
        {
            this.EQ_InputOrder = new HashSet<EQ_InputOrder>();
            this.EQ_Order_Details = new HashSet<EQ_Order_Details>();
        }
    
        public int Order_ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public Nullable<int> StoreIDReceive { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryLocation { get; set; }
        public string Regulations { get; set; }
        public string PaymentTerm { get; set; }
        public string Quality { get; set; }
        public string Warranty { get; set; }
        public string OtherInfo { get; set; }
        public string FollowUpPerson { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<EQ_InputOrder> EQ_InputOrder { get; set; }
        public virtual ICollection<EQ_Order_Details> EQ_Order_Details { get; set; }
        public virtual EQ_Requests EQ_Requests { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
