//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQ_Quotes
    {
        public EQ_Quotes()
        {
            this.EQ_InputQuote = new HashSet<EQ_InputQuote>();
            this.EQ_QuoteSupplier = new HashSet<EQ_QuoteSupplier>();
        }
    
        public int Quote_ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public string FollowUpPerson { get; set; }
        public string Assessment { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<EQ_InputQuote> EQ_InputQuote { get; set; }
        public virtual EQ_Requests EQ_Requests { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<EQ_QuoteSupplier> EQ_QuoteSupplier { get; set; }
    }
}
