//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQ_Requests
    {
        public EQ_Requests()
        {
            this.EQ_Contracts = new HashSet<EQ_Contracts>();
            this.EQ_Orders = new HashSet<EQ_Orders>();
            this.EQ_Quotes = new HashSet<EQ_Quotes>();
            this.EQ_Request_Details = new HashSet<EQ_Request_Details>();
        }
    
        public int RequestID { get; set; }
        public string ProdCode { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string RequestForWhen { get; set; }
        public string Description { get; set; }
        public Nullable<int> StoreIDSend { get; set; }
        public Nullable<int> StoreIDReceive { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<EQ_Contracts> EQ_Contracts { get; set; }
        public virtual ICollection<EQ_Orders> EQ_Orders { get; set; }
        public virtual ICollection<EQ_Quotes> EQ_Quotes { get; set; }
        public virtual ICollection<EQ_Request_Details> EQ_Request_Details { get; set; }
        public virtual Store ReceiveStore { get; set; }
        public virtual Store SendStore { get; set; }
    }
}
