//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EQ_Input_Details = new HashSet<EQ_Input_Details>();
            this.EQ_Inventory = new HashSet<EQ_Inventory>();
            this.EQ_Order_Details = new HashSet<EQ_Order_Details>();
            this.EQ_Output_Details = new HashSet<EQ_Output_Details>();
            this.EQ_Request_Details = new HashSet<EQ_Request_Details>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> CatID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> USPrice { get; set; }
        public Nullable<decimal> VNPrice { get; set; }
        public Nullable<System.DateTime> LastBoughtDate { get; set; }
        public string IMEI { get; set; }
        public string Origin { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<int> Creator { get; set; }
    
        public virtual EQ_Categories EQ_Categories { get; set; }
        public virtual ICollection<EQ_Input_Details> EQ_Input_Details { get; set; }
        public virtual ICollection<EQ_Inventory> EQ_Inventory { get; set; }
        public virtual ICollection<EQ_Order_Details> EQ_Order_Details { get; set; }
        public virtual ICollection<EQ_Output_Details> EQ_Output_Details { get; set; }
        public virtual ICollection<EQ_Request_Details> EQ_Request_Details { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
