//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_Orders
    {
        public Mat_Orders()
        {
            this.Mat_Inputs = new HashSet<Mat_Inputs>();
            this.Mat_Order_Details = new HashSet<Mat_Order_Details>();
        }
    
        public int OrderID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string OrderReason { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryLocation { get; set; }
        public string Receiver { get; set; }
        public string OtherInfo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Mat_Inputs> Mat_Inputs { get; set; }
        public virtual ICollection<Mat_Order_Details> Mat_Order_Details { get; set; }
        public virtual Mat_Requests Mat_Requests { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
