//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_Input_Details
    {
        public int InDetail_ID { get; set; }
        public Nullable<int> InputID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> USPrice { get; set; }
        public Nullable<decimal> VNPrice { get; set; }
        public string WarrantyTime { get; set; }
        public Nullable<int> DeptIDReceive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Mat_Inputs Mat_Inputs { get; set; }
        public virtual Material Material { get; set; }
    }
}
