//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_Request_Details
    {
        public int ReqDetail_ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<double> RequestedQuantity { get; set; }
        public Nullable<double> ApprovedQuantity { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Mat_Requests Mat_Requests { get; set; }
        public virtual Material Material { get; set; }
    }
}
