//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_Requests
    {
        public Mat_Requests()
        {
            this.Mat_Orders = new HashSet<Mat_Orders>();
            this.Mat_Request_Details = new HashSet<Mat_Request_Details>();
        }
    
        public int RequestID { get; set; }
        public string ProdCode { get; set; }
        public string Code { get; set; }
        public Nullable<int> DeptIDSend { get; set; }
        public Nullable<int> DeptIDReceive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RequestForWhen { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Department ReceiveDepartment { get; set; }
        public virtual Department SendDepartment { get; set; }
        public virtual ICollection<Mat_Orders> Mat_Orders { get; set; }
        public virtual ICollection<Mat_Request_Details> Mat_Request_Details { get; set; }
    }
}
