//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_Inputs
    {
        public Mat_Inputs()
        {
            this.Mat_Input_Details = new HashSet<Mat_Input_Details>();
        }
    
        public int Input_ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Mat_Input_Details> Mat_Input_Details { get; set; }
        public virtual Mat_Orders Mat_Orders { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
