//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Mat_Input_Details = new HashSet<Mat_Input_Details>();
            this.Mat_Order_Details = new HashSet<Mat_Order_Details>();
            this.Mat_Repair_Details = new HashSet<Mat_Repair_Details>();
            this.Mat_Request_Details = new HashSet<Mat_Request_Details>();
        }
    
        public int Material_ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> CatID { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> USPrice { get; set; }
        public Nullable<decimal> VNPrice { get; set; }
        public Nullable<System.DateTime> LastBoughtDate { get; set; }
        public string IMEI { get; set; }
        public string Origin { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
    
        public virtual Mat_Categories Mat_Categories { get; set; }
        public virtual ICollection<Mat_Input_Details> Mat_Input_Details { get; set; }
        public virtual ICollection<Mat_Order_Details> Mat_Order_Details { get; set; }
        public virtual ICollection<Mat_Repair_Details> Mat_Repair_Details { get; set; }
        public virtual ICollection<Mat_Request_Details> Mat_Request_Details { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
