//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    
    public partial class PGSDBEntities : DbContext
    {
        public PGSDBEntities()
            : base("name=PGSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car_Drivers> Car_Drivers { get; set; }
        public DbSet<Car_Maintenances> Car_Maintenances { get; set; }
        public DbSet<Car_Schedules> Car_Schedules { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<CoType> CoTypes { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EQ_Categories> EQ_Categories { get; set; }
        public DbSet<EQ_Contracts> EQ_Contracts { get; set; }
        public DbSet<EQ_Input_Details> EQ_Input_Details { get; set; }
        public DbSet<EQ_InputOrder> EQ_InputOrder { get; set; }
        public DbSet<EQ_InputQuote> EQ_InputQuote { get; set; }
        public DbSet<EQ_Inputs> EQ_Inputs { get; set; }
        public DbSet<EQ_Inventory> EQ_Inventory { get; set; }
        public DbSet<EQ_Order_Details> EQ_Order_Details { get; set; }
        public DbSet<EQ_Orders> EQ_Orders { get; set; }
        public DbSet<EQ_Output_Details> EQ_Output_Details { get; set; }
        public DbSet<EQ_Outputs> EQ_Outputs { get; set; }
        public DbSet<EQ_Quotes> EQ_Quotes { get; set; }
        public DbSet<EQ_QuoteSupplier> EQ_QuoteSupplier { get; set; }
        public DbSet<EQ_Request_Details> EQ_Request_Details { get; set; }
        public DbSet<EQ_Requests> EQ_Requests { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Mat_Categories> Mat_Categories { get; set; }
        public DbSet<Mat_Input_Details> Mat_Input_Details { get; set; }
        public DbSet<Mat_Inputs> Mat_Inputs { get; set; }
        public DbSet<Mat_Order_Details> Mat_Order_Details { get; set; }
        public DbSet<Mat_Orders> Mat_Orders { get; set; }
        public DbSet<Mat_Repair_Details> Mat_Repair_Details { get; set; }
        public DbSet<Mat_Repairs> Mat_Repairs { get; set; }
        public DbSet<Mat_Request_Details> Mat_Request_Details { get; set; }
        public DbSet<Mat_Requests> Mat_Requests { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<StatusCollection> StatusCollections { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetMaxRequestCode(Nullable<int> storeID)
        {
            var storeIDParameter = storeID.HasValue ?
                new ObjectParameter("StoreID", storeID) :
                new ObjectParameter("StoreID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetMaxRequestCode", storeIDParameter);
        }
    }
}
