//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCollection
    {
        public int Status_ID { get; set; }
        public string StatusName { get; set; }
        public string Abbreviation { get; set; }
        public string StatusGroup { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
