//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.EQ_Contracts = new HashSet<EQ_Contracts>();
            this.EQ_Inputs = new HashSet<EQ_Inputs>();
            this.EQ_Inventory = new HashSet<EQ_Inventory>();
            this.EQ_Orders = new HashSet<EQ_Orders>();
            this.EQ_Outputs = new HashSet<EQ_Outputs>();
            this.EQ_Quotes = new HashSet<EQ_Quotes>();
            this.EQ_Requests_ReceiveStore = new HashSet<EQ_Requests>();
            this.EQ_Requests_SendStore = new HashSet<EQ_Requests>();
        }
    
        public int Store_ID { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string StoreType { get; set; }
        public string StoreInfo { get; set; }
        public string StoreAddress { get; set; }
        public string PersonInCharge { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
    
        public virtual ICollection<EQ_Contracts> EQ_Contracts { get; set; }
        public virtual ICollection<EQ_Inputs> EQ_Inputs { get; set; }
        public virtual ICollection<EQ_Inventory> EQ_Inventory { get; set; }
        public virtual ICollection<EQ_Orders> EQ_Orders { get; set; }
        public virtual ICollection<EQ_Outputs> EQ_Outputs { get; set; }
        public virtual ICollection<EQ_Quotes> EQ_Quotes { get; set; }
        public virtual ICollection<EQ_Requests> EQ_Requests_ReceiveStore { get; set; }
        public virtual ICollection<EQ_Requests> EQ_Requests_SendStore { get; set; }
    }
}
