//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.EQ_Contracts = new HashSet<EQ_Contracts>();
            this.EQ_Orders = new HashSet<EQ_Orders>();
            this.EQ_QuoteSupplier = new HashSet<EQ_QuoteSupplier>();
            this.Mat_Inputs = new HashSet<Mat_Inputs>();
            this.Mat_Orders = new HashSet<Mat_Orders>();
            this.Mat_Repair_Details = new HashSet<Mat_Repair_Details>();
        }
    
        public int SupplierID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> CoTypeID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string AccountNo { get; set; }
        public string TaxNo { get; set; }
        public string ContactPerson { get; set; }
        public string ContactMobile { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updator { get; set; }
    
        public virtual CoType CoType { get; set; }
        public virtual ICollection<EQ_Contracts> EQ_Contracts { get; set; }
        public virtual ICollection<EQ_Orders> EQ_Orders { get; set; }
        public virtual ICollection<EQ_QuoteSupplier> EQ_QuoteSupplier { get; set; }
        public virtual ICollection<Mat_Inputs> Mat_Inputs { get; set; }
        public virtual ICollection<Mat_Orders> Mat_Orders { get; set; }
        public virtual ICollection<Mat_Repair_Details> Mat_Repair_Details { get; set; }
    }
}
