//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Equipments = new HashSet<Equipment>();
            this.Materials = new HashSet<Material>();
        }
    
        public int Unit_ID { get; set; }
        public string UCode { get; set; }
        public string UName { get; set; }
        public string UGroup { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UNotes { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
    }
}
