//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_process {
            get {
                object obj = ResourceManager.GetObject("add_process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ai_file {
            get {
                object obj = ResourceManager.GetObject("ai_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap airplane_24 {
            get {
                object obj = ResourceManager.GetObject("airplane_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bang_bao_gia__32 {
            get {
                object obj = ResourceManager.GetObject("bang bao gia -32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_arrow_down {
            get {
                object obj = ResourceManager.GetObject("blue_arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_arrow_up {
            get {
                object obj = ResourceManager.GetObject("blue_arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap businesswoman_man {
            get {
                object obj = ResourceManager.GetObject("businesswoman_man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Car {
            get {
                object obj = ResourceManager.GetObject("Car", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chuc_danh {
            get {
                object obj = ResourceManager.GetObject("chuc danh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chung_loai_vat_tu {
            get {
                object obj = ResourceManager.GetObject("chung loai vat tu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chung_loai_vpp {
            get {
                object obj = ResourceManager.GetObject("chung loai vpp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer_process {
            get {
                object obj = ResourceManager.GetObject("computer_process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_don_dat_hang_32 {
            get {
                object obj = ResourceManager.GetObject("danh muc don dat hang-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_hop_dong_32 {
            get {
                object obj = ResourceManager.GetObject("danh muc hop dong-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_phieu_nhap_kho_32 {
            get {
                object obj = ResourceManager.GetObject("danh muc phieu nhap kho-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_phieu_xuat_kho {
            get {
                object obj = ResourceManager.GetObject("danh muc phieu xuat kho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_phieu_xuat_kho_32 {
            get {
                object obj = ResourceManager.GetObject("danh muc phieu xuat kho-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danh_muc_phieu_yeu_cau_32 {
            get {
                object obj = ResourceManager.GetObject("danh muc phieu yeu cau-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap don_dat_hang_32 {
            get {
                object obj = ResourceManager.GetObject("don dat hang-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap driver {
            get {
                object obj = ResourceManager.GetObject("driver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GianKhoan {
            get {
                object obj = ResourceManager.GetObject("GianKhoan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hop_dong_32 {
            get {
                object obj = ResourceManager.GetObject("hop dong-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lich_cong_tac {
            get {
                object obj = ResourceManager.GetObject("lich cong tac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loai_hinh_cong_ty {
            get {
                object obj = ResourceManager.GetObject("loai hinh cong ty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maintenance_32 {
            get {
                object obj = ResourceManager.GetObject("Maintenance-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaintenanceList_32 {
            get {
                object obj = ResourceManager.GetObject("MaintenanceList-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mau_bieu_bao_cao_1 {
            get {
                object obj = ResourceManager.GetObject("mau bieu bao cao 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mau_bieu_bao_cao_3 {
            get {
                object obj = ResourceManager.GetObject("mau bieu bao cao 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mau_bieu_bao_cao_5 {
            get {
                object obj = ResourceManager.GetObject("mau bieu bao cao 5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mau_bieu_bao_cao_6 {
            get {
                object obj = ResourceManager.GetObject("mau bieu bao cao 6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nguoi_su_dung {
            get {
                object obj = ResourceManager.GetObject("nguoi su dung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nha_cung_cap {
            get {
                object obj = ResourceManager.GetObject("nha cung cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nhan_vien {
            get {
                object obj = ResourceManager.GetObject("nhan vien", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_nhap_kho_32 {
            get {
                object obj = ResourceManager.GetObject("phieu nhap kho-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_xuat_kho_32 {
            get {
                object obj = ResourceManager.GetObject("phieu xuat kho-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_yeu_cau {
            get {
                object obj = ResourceManager.GetObject("phieu yeu cau", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phieu_yeu_cau_32 {
            get {
                object obj = ResourceManager.GetObject("phieu yeu cau-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phong_ban {
            get {
                object obj = ResourceManager.GetObject("phong ban", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PTSC_PGS {
            get {
                object obj = ResourceManager.GetObject("PTSC PGS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ROV {
            get {
                object obj = ResourceManager.GetObject("ROV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shuffle_24 {
            get {
                object obj = ResourceManager.GetObject("shuffle_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap store {
            get {
                object obj = ResourceManager.GetObject("store", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap truck {
            get {
                object obj = ResourceManager.GetObject("truck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unit {
            get {
                object obj = ResourceManager.GetObject("Unit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vat_tu {
            get {
                object obj = ResourceManager.GetObject("vat tu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VPP {
            get {
                object obj = ResourceManager.GetObject("VPP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xe_hoi {
            get {
                object obj = ResourceManager.GetObject("xe hoi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
